### ISSUE TITLE
Add an org.apache.ivy dependency in order to be able to use @Grab in scripts smoothly

### ISSUE THREAD

**Issue by Haybu** [spring-cloud-stream-app-starters/scriptable-transform#8]

**Comment by artembilan** [comment]
Hello, @Haybu !

Thank you for the issue!

May we have a sample script to be sure what you mean?
And that one can be used for testing purpose during the fix.

Also contribution is welcome!

**Comment by Haybu** [comment]
Thanks @artembilan 

My use case was with a Groovy script that uses an instance of `groovy.util.XmlParser`. The application threw `java.lang.ClassNotFoundException: org.apache.ivy.plugins.resolver.DependencyResolver` exception. I expect this will be resolved if `groovy-all` is added part of issue #9 

Moreover, it would be a useful and convenient feature to be able to `@Grab` and use arbitrary library aside from what is included by default. To be able to resolve the "grabbed" deps in a script, `org.apache.ivy` is needed to be added to the project. 

For testing sake, consider this script that uses a library to convert a groovy statement to Javascript. 

```groovy
@Grab('org.grooscript:grooscript:1.3.0')
import org.grooscript.GrooScript
GrooScript.convert 'def age = 18'    
```

We can test with this in a stream transformer for instance to convert a payload of simple groovy statements. 

```groovy
GrooScript.convert(new String(payload))
```

**Comment by artembilan** [comment]
@Haybu ,

Thanks for the feedback!

Well, right now with my fix in that PR you are not going to have problems with the `groovy.util.XmlParser`, because there is already an explicit `groovy-xml`.

I'm not sure that we can use that `groovy-all`. It's not a jar anymore and it is not really a BOM. 
See my comment in the: https://github.com/spring-projects/spring-boot/issues/15468.

Re. `@Grab`, as we discussed with you in Slack, there are no objections and we definitely should add that `org.apache.ivy` explicit dependency since we can't know what end-user would like to use in his/her target script.
Your sample about `GrooScript` is really cool and that is one of the use-case which can't be covered just with the Groovy dependencies.

So, if you are good with what we have so far, I'd like to ask you about contribution and let's continue discussion already on PR from you! If that will be necessary, of course...

Thanks again!

**Comment by Haybu** [comment]
Great, thanks Artem. I'll be on it soon 👍

**Comment by Haybu** [comment]
Hi @artembilan. Please take a look into my PR and let me know how it looks. I have tried it out with the above groovy script example and it works well "grabbing" the dep.
